### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#1]
### Roadmap
- [x] Example Readmes
- [x] Integrate CPAN feedback from @noffle https://github.com/RichardLitt/standard-readme/issues/3
- [x] Generator with yo as an implicit dependency. https://github.com/RichardLitt/standard-readme/issues/6
- [x] Try to merge some standard- and common-readme ideas into one readme. https://github.com/RichardLitt/standard-readme/issues/10
  - [x] Make it less js-specific https://github.com/RichardLitt/standard-readme/issues/8
- [ ] Linter https://github.com/RichardLitt/standard-readme/issues/5
- [x] Use on specific IPFS Readmes, get feedback from Protocol Lab developers
- [x] Usage tests: Get a bunch of people to use it in their projects and gather feedback on whether it's useful and how we can improve it to match real people's need.
- [ ] Press Release
  - [ ] Medium Article
  - [ ] Post on HackerNews
  - [ ] Post on Reddit
  - [ ] IPFS Newsletter (again)
  - [ ] npm weekly (they might pick this up -- they often take community modules)
- [x] Create badge. Specify as optional.
- [ ] Plugins
  - [ ] Build Atom plugin
  - [ ] Build Sublime plugin

**Comment by RichardLitt** [comment]
Title can now be validated using [wooorm/remark](//github.com/wooorm/remark) and [RichardLitt/remark-title](//github.com/RichardLitt/remark-title).

**Comment by RichardLitt** [comment]
Note: Keep up to date and check with https://github.com/ipfs/project-repos/issues/1.

**Comment by mafintosh** [comment]
After looking through my/other people's repos i think 

> A clear description in the GitHub description field, of over 150 characters.

Should be changed to

> A clear description in the GitHub description field

**Comment by RichardLitt** [comment]
Changed. Working on a module for getting and setting that.

**Comment by RichardLitt** [comment]
Created [remark-lint-appropriate-heading](https://github.com/RichardLitt/remark-lint-appropriate-heading) to make sure that the heading matches the dir name of the Readme. Works for top level readmes.

**Comment by RichardLitt** [comment]
I am going to track the Linter and the Generator in their appropriate issues. Since the spec is done, and those are the main things to do, I am going to close this issue for now. Reopen to discuss.

**Comment by RichardLitt** [comment]
I have edited the Roadmap in the first comment. Let's go!
